### PR TITLE
Make "drop" issue the command "r_drawviewmodel 0" instead of dropping weapons.

### PR DESCRIPTION
**Pull request by mxpph**
Dropping weapons can distract players so instead of actually dropping the weapons just hide them from view.

### CODE REVIEW

**Comment by fireblizzard** [comment]
This is not a complete solution, because the player may have `cl_filterstuffcmd` set to `1`, which blocks lots of [commands](https://developer.valvesoftware.com/wiki/Admin_Slowhacking#cl_filterstuffcmd_1) from being applied in the client, including `r_drawviewmodel`.

So I see a couple of problems:
- An evil player that drops weapons not accidentally, but with the purpose of bothering other players, will be able to continue distracting players. I believe that `cl_filterstuffcmd` is set to 0 by default, but they may know about it and set it to `1`.
- For players new to AG or GoldSrc this might be harmful, as they may have a config from some friend, which is quite a common case among the ones getting into AG for the deathmatch side of the game (and may join bhop servers occasionally), and drop weapons accidentally as the config has some bind for it and they're not used to it. Then, suddenly they can't see their weapon models, they're not used to that and they don't have the HUD thingy that tells you what weapon you're using, and thus can't play deathmatch properly until they get help from veterans to revert the change in their config. This may be worded a bit too dramatically, but if it can happen, it will happen.

Ideas:
- Make a user setting to toggle weaponbox visibility, and perhaps to toggle the sound of taking a weaponbox too?
- Make a user setting to start without weapons, that is, weaponstrip them as soon as they spawn, or with some delay. This is not a complete solution, but it would be nice to have this feature.

**Comment by mxpph** [comment]
Well, some players like having their weapons, some don't. But it is distracting when they are dropped in matches. Having players start without weapons would be bad for the people who like seeing their weapons. Maybe just blocking "drop" but not issuing the "r_drawviewmodel 0" command? It could show a HUD/chat message saying that dropping is disabled and you can use "r_drawviewmodel 0" or some other alternative. 

Of course if there is a way to show dropped packs to clients who dropped them only, like a /invis for packs, then I think that would be the best solution.

**Comment by fireblizzard** [comment]
Players who want to see their weapons would continue to see them, it would just be a user preference to start without weapons, like we're doing for HUD settings and others.

Blocking `drop` and showing a message about `r_drawviewmodel` might be a valid alternative.

I think it's possible to hide weaponboxes/packs depending on user preference, probably within `Fw_FmAddToFullPackPost()`.

**Comment by fireblizzard** [comment]
Tested, works fine. Merged into unstable.

**Pull request closed without merging**
